dbt_project:
  outputs:
    dev:
      dbname: green_taxi
      host: postgres
      pass: airflow
      port: 5432
      threads: 1
      schema: intermediate
      type: postgres
      user: airflow
  target: dev
